# Generated by Django 5.0.6 on 2026-05-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, default='Dr.', max_length=40)),
                ('specialty', models.CharField(choices=[('general', 'General Practice'), ('internal', 'Internal Medicine'), ('anesthesia', 'Anesthesiology'), ('surgery', 'Surgery'), ('obgyn', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('neurology', 'Neurology'), ('cardiology', 'Cardiology'), ('emergency', 'Emergency Medicine'), ('family', 'Family Medicine'), ('other', 'Other')], default='general', max_length=30)),
                ('facility', models.CharField(blank=True, max_length=120)),
                ('default_note_style', models.CharField(choices=[('soap', 'SOAP (compartmentalized)'), ('narrative', 'Narrative (free-form)'), ('chart', 'Chart / progress note')], default='soap', max_length=20)),
                ('long_form_default', models.BooleanField(default=False)),
                ('font_scale', models.PositiveSmallIntegerField(default=100)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'System')], default='light', max_length=10)),
                ('custom_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
