# Generated by Django 5.0.6 on 2026-05-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('clinician', 'Clinician'), ('lead', 'Clinical lead'), ('admin', 'Administrator')], default='clinician', max_length=20),
        ),
    ]
