# Generated by Django 5.0.6 on 2026-06-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctorprofile_login_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='preferred_language',
            field=models.CharField(choices=[('jam_Latn', 'Jamaican Creole (Patois)'), ('eng_Latn', 'English'), ('spa_Latn', 'Spanish'), ('fra_Latn', 'French'), ('hat_Latn', 'Haitian Creole'), ('por_Latn', 'Portuguese'), ('wol_Latn', 'Wolof'), ('kin_Latn', 'Kinyarwanda')], default='jam_Latn', help_text='Language spoken during consultations — used by the ASR model.', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('clinician', 'Clinician'), ('lead', 'Clinical lead'), ('admin', 'Administrator'), ('scribe', 'Medical scribe'), ('ed_nurse', 'ED nurse'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], default='clinician', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_mode', models.CharField(choices=[('off', 'Off — normal operation'), ('limited', 'Test mode — limit each non-admin to a few notes'), ('locked', 'Locked — block all non-admin usage')], default='off', max_length=10)),
                ('note_limit', models.PositiveSmallIntegerField(default=1, help_text='In Test mode, the max number of sessions a non-admin may create.')),
                ('message', models.CharField(blank=True, default='', help_text='Optional override for the message non-admins see. Blank uses a sensible default.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform control',
                'verbose_name_plural': 'Platform control',
            },
        ),
    ]
