# Generated by Django 5.0.6 on 2026-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_doctorprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('clinician', 'Doctor / Clinician'), ('lead', 'Clinical lead'), ('admin', 'Administrator'), ('nurse', 'Nurse'), ('ed_nurse', 'ED nurse'), ('scribe', 'Medical scribe'), ('receptionist', 'Receptionist'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab technician')], default='clinician', max_length=20),
        ),
    ]
