# Generated by Django 5.0.6 on 2026-07-11 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_doctorprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='preferred_language',
            field=models.CharField(choices=[('jam_Latn', 'Jamaican Creole (Patois)'), ('eng_Latn', 'English'), ('spa_Latn', 'Spanish'), ('fra_Latn', 'French'), ('hat_Latn', 'Haitian Creole'), ('por_Latn', 'Portuguese'), ('wol_Latn', 'Wolof'), ('kin_Latn', 'Kinyarwanda')], default='jam_Latn', help_text='Language spoken during consultations - used by the ASR model.', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformcontrol',
            name='demo_mode',
            field=models.CharField(choices=[('off', 'Off - normal operation'), ('limited', 'Test mode - limit each non-admin to a few notes'), ('locked', 'Locked - block all non-admin usage')], default='off', max_length=10),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rapid_access', 'Rapid access (possible scraping)'), ('impossible_travel', 'Impossible travel (possible account takeover)'), ('error_probing', 'Endpoint probing (403/401 sweep)'), ('login_failed', 'Failed login')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_se_event_t_67c552_idx'), models.Index(fields=['ip', 'created_at'], name='accounts_se_ip_393b1a_idx')],
            },
        ),
    ]
