# Generated by Django 5.0.6 on 2026-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctorprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='sound_effects',
            field=models.BooleanField(default=True, help_text='Play start/cancel/success chimes during recording.'),
        ),
    ]
