# Generated by Django 5.0.6 on 2026-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctorprofile_sound_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='highlight_terms',
            field=models.BooleanField(default=True, help_text='Persistently highlight medications (and key terms) in the note review.'),
        ),
    ]
