# Generated by Django 5.0.6 on 2026-05-13 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scribe", "0011_scribesession_nullable_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("private_clinic", "Private clinic"),
                            ("public_health_centre", "Public health centre"),
                            ("private_hospital", "Private hospital"),
                            ("community_health", "Community health service"),
                        ],
                        default="private_clinic",
                        max_length=40,
                    ),
                ),
                (
                    "parish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Kingston", "Kingston"),
                            ("St. Andrew", "St. Andrew"),
                            ("St. Thomas", "St. Thomas"),
                            ("Portland", "Portland"),
                            ("St. Mary", "St. Mary"),
                            ("St. Ann", "St. Ann"),
                            ("Trelawny", "Trelawny"),
                            ("St. James", "St. James"),
                            ("Hanover", "Hanover"),
                            ("Westmoreland", "Westmoreland"),
                            ("St. Elizabeth", "St. Elizabeth"),
                            ("Manchester", "Manchester"),
                            ("Clarendon", "Clarendon"),
                            ("St. Catherine", "St. Catherine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nhf_facility_code", models.CharField(blank=True, max_length=20)),
                ("subscription_tier", models.CharField(default="trial", max_length=20)),
                (
                    "subscription_status",
                    models.CharField(default="active", max_length=20),
                ),
                ("billing_currency", models.CharField(default="JMD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField()),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("acute", "Acute"),
                            ("chronic_followup", "Chronic follow-up"),
                            ("antenatal", "Antenatal"),
                            ("well_child", "Well child"),
                            ("emergency", "Emergency"),
                            ("immunisation", "Immunisation"),
                            ("school_health", "School health"),
                            ("home_visit", "Home visit"),
                            ("telehealth", "Telehealth"),
                        ],
                        default="acute",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked in"),
                            ("triage", "In triage"),
                            ("with_doctor", "With doctor"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("queue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "scheduled_for",
                    "queue_number",
                    "patient__legal_last_name",
                ),
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encounter_date", models.DateField()),
                ("encounter_time", models.TimeField(blank=True, null=True)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("acute", "Acute"),
                            ("chronic_followup", "Chronic follow-up"),
                            ("antenatal", "Antenatal"),
                            ("well_child", "Well child"),
                            ("emergency", "Emergency"),
                            ("immunisation", "Immunisation"),
                            ("school_health", "School health"),
                            ("home_visit", "Home visit"),
                            ("telehealth", "Telehealth"),
                        ],
                        default="acute",
                        max_length=40,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("history_of_presenting_illness", models.TextField(blank=True)),
                ("review_of_systems", models.TextField(blank=True)),
                ("physical_examination", models.TextField(blank=True)),
                ("assessment_notes", models.TextField(blank=True)),
                ("plan_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_instructions", models.TextField(blank=True)),
                ("sick_leave_start", models.DateField(blank=True, null=True)),
                ("sick_leave_end", models.DateField(blank=True, null=True)),
                ("sick_leave_diagnosis", models.CharField(blank=True, max_length=200)),
                ("herbal_remedies", models.TextField(blank=True)),
                (
                    "encounter_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("signed", "Signed"),
                            ("amended", "Amended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="emr.encounter",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="emr.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_encounters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scribe_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_encounters",
                        to="scribe.scribesession",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_encounters_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_encounters_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-encounter_date", "-encounter_time", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("receptionist", "Receptionist"),
                            ("admin", "Organisation admin"),
                            ("system_admin", "System admin"),
                        ],
                        default="doctor",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="emr.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("organisation__name", "user__username"),
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_first_name", models.CharField(max_length=100)),
                ("legal_last_name", models.CharField(max_length=100)),
                ("preferred_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("intersex", "Intersex"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("gender_identity", models.CharField(blank=True, max_length=50)),
                ("nhf_card_number", models.CharField(blank=True, max_length=20)),
                ("trn", models.CharField(blank=True, max_length=9)),
                ("nids_number", models.CharField(blank=True, max_length=30)),
                ("street_address", models.TextField(blank=True)),
                ("community", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "parish",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Kingston", "Kingston"),
                            ("St. Andrew", "St. Andrew"),
                            ("St. Thomas", "St. Thomas"),
                            ("Portland", "Portland"),
                            ("St. Mary", "St. Mary"),
                            ("St. Ann", "St. Ann"),
                            ("Trelawny", "Trelawny"),
                            ("St. James", "St. James"),
                            ("Hanover", "Hanover"),
                            ("Westmoreland", "Westmoreland"),
                            ("St. Elizabeth", "St. Elizabeth"),
                            ("Manchester", "Manchester"),
                            ("Clarendon", "Clarendon"),
                            ("St. Catherine", "St. Catherine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone_primary", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("phone_is_whatsapp", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("next_of_kin_name", models.CharField(blank=True, max_length=200)),
                (
                    "next_of_kin_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                ("nhf_card_programme", models.CharField(blank=True, max_length=100)),
                ("private_insurer_name", models.CharField(blank=True, max_length=100)),
                ("private_policy_number", models.CharField(blank=True, max_length=50)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("ethnicity", models.CharField(blank=True, max_length=50)),
                (
                    "nationality",
                    models.CharField(blank=True, default="Jamaican", max_length=50),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Jamaican Patois", "Jamaican Patois"),
                        ],
                        default="English",
                        max_length=50,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("herbal_history", models.TextField(blank=True)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("written", "Written"),
                            ("verbal", "Verbal"),
                            ("electronic", "Electronic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("deceased", models.BooleanField(default=False)),
                ("deceased_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_patients_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("legal_last_name", "legal_first_name", "date_of_birth"),
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drug_name_generic", models.CharField(max_length=200)),
                ("drug_name_brand", models.CharField(blank=True, max_length=200)),
                ("is_ven_listed", models.BooleanField(default=False)),
                ("rxnorm_code", models.CharField(blank=True, max_length=20)),
                (
                    "dose_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("dose_unit", models.CharField(blank=True, max_length=20)),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oral", "Oral"),
                            ("IV", "IV"),
                            ("IM", "IM"),
                            ("SC", "SC"),
                            ("topical", "Topical"),
                            ("inhaled", "Inhaled"),
                            ("sublingual", "Sublingual"),
                            ("rectal", "Rectal"),
                            ("ophthalmic", "Ophthalmic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("frequency", models.CharField(blank=True, max_length=50)),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("refills_authorised", models.PositiveSmallIntegerField(default=0)),
                ("refills_remaining", models.PositiveSmallIntegerField(default=0)),
                ("pharmacy_instructions", models.TextField(blank=True)),
                ("interaction_flags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("discontinued", "Discontinued"),
                            ("completed", "Completed"),
                            ("on_hold", "On hold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reason_discontinued", models.TextField(blank=True)),
                ("ai_suggested", models.BooleanField(default=False)),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="emr.encounter",
                    ),
                ),
                (
                    "prescribing_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_medications_prescribed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "drug_name_generic"),
            },
        ),
        migrations.CreateModel(
            name="Immunisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("nip_schedule_code", models.CharField(blank=True, max_length=20)),
                (
                    "dose_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("date_given", models.DateField()),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left_arm", "Left arm"),
                            ("right_arm", "Right arm"),
                            ("left_thigh", "Left thigh"),
                            ("right_thigh", "Right thigh"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[("IM", "IM"), ("SC", "SC"), ("oral", "Oral")],
                        max_length=20,
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_immunisations_administered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="immunisations",
                        to="emr.encounter",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunisations",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_given", "vaccine_name"),
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="emr.patient",
            ),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icd10_code", models.CharField(max_length=10)),
                ("icd10_description", models.CharField(blank=True, max_length=500)),
                ("snomed_code", models.CharField(blank=True, max_length=20)),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("resolution_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("chronic", "Chronic"),
                            ("suspected", "Suspected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("diagnosis_rank", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("ai_suggested", models.BooleanField(default=False)),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "diagnosing_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_diagnoses_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="emr.encounter",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("diagnosis_rank", "icd10_code"),
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="emr.patient",
            ),
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allergen_name", models.CharField(max_length=200)),
                (
                    "allergen_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drug", "Drug"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reaction_type", models.CharField(blank=True, max_length=200)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("anaphylaxis", "Anaphylaxis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("unconfirmed", "Unconfirmed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("allergen_name",),
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiving_facility", models.CharField(max_length=200)),
                ("receiving_specialty", models.CharField(blank=True, max_length=100)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("clinical_summary", models.TextField(blank=True)),
                (
                    "current_medications_snapshot",
                    models.JSONField(blank=True, default=list),
                ),
                ("referral_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("received", "Received"),
                            ("responded", "Responded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("response_notes", models.TextField(blank=True)),
                ("response_date", models.DateField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="emr.encounter",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="emr.patient",
                    ),
                ),
                (
                    "referring_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-referral_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Vital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "bp_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bp_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pulse_bpm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "respiratory_rate",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "blood_glucose_mmol",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "muac_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("pain_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "head_circumference_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "weight_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "height_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "bmi_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vitals",
                        to="emr.encounter",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="emr.organisation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="emr.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_vitals_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=50)),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("detail", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="emr.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "created_at"],
                        name="emr_auditlo_organis_d0c549_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="emr_auditlo_resourc_6d7bb2_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="organisationmembership",
            constraint=models.UniqueConstraint(
                fields=("organisation", "user"), name="emr_unique_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["organisation", "legal_last_name", "legal_first_name"],
                name="emr_patient_organis_c5ed04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["organisation", "nhf_card_number"],
                name="emr_patient_organis_082940_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["organisation", "trn"], name="emr_patient_organis_70d543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["organisation", "patient", "encounter_date"],
                name="emr_encount_organis_a999bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["organisation", "encounter_status", "encounter_date"],
                name="emr_encount_organis_ab5dbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["organisation", "scheduled_for", "status"],
                name="emr_appoint_organis_c5382c_idx",
            ),
        ),
    ]
