# Generated by Django 5.0.6 on 2026-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_encounteraddendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='billing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='provider_seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organisation',
            name='subscription_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('scribe', 'Scribe only (per provider)'), ('practice', 'Practice — Scribe + EMR'), ('emr', 'EMR only (per facility)')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('scribe', 'Medical scribe'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab technician'), ('admin', 'Organisation admin'), ('system_admin', 'System admin')], default='doctor', max_length=20),
        ),
    ]
