# Generated by Django 5.0.6 on 2026-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_organisation_billing_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('scribe', 'Scribe only (per provider)'), ('practice', 'Practice - Scribe + EMR'), ('emr', 'EMR only (per facility)')], default='trial', max_length=20),
        ),
    ]
