# Generated by Django 5.0.6 on 2026-05-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScribeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('chief_complaint', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='scribe_audio/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('dictation', 'Post-encounter dictation'), ('ambient', 'Ambient recording'), ('text', 'Direct text entry')], default='dictation', max_length=20)),
                ('note_format', models.CharField(choices=[('soap', 'SOAP (compartmentalized)'), ('narrative', 'Narrative (free-form)'), ('chart', 'Chart / progress note')], default='soap', max_length=20)),
                ('length_mode', models.CharField(choices=[('normal', 'Normal'), ('long_form', 'Long form')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recording', 'Recording'), ('transcribing', 'Transcribing'), ('generating', 'Generating note'), ('review', 'Ready for review'), ('finalized', 'Finalized'), ('error', 'Error')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scribe_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Session created'), ('uploaded', 'Audio uploaded'), ('transcribed', 'Transcription complete'), ('generated', 'Note generated'), ('verified', 'Note verified'), ('edited', 'Doctor edited'), ('exported', 'Exported'), ('finalized', 'Finalized'), ('error', 'Error')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scribe.scribesession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('full_note', models.TextField(blank=True)),
                ('edited_note', models.TextField(blank=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('review_completed', models.BooleanField(default=False)),
                ('export_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='scribe.scribesession')),
            ],
        ),
    ]
