# Generated by Django 5.0.6 on 2026-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0006_drop_legacy_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribesession',
            name='active_conditions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scribesession',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='scribesession',
            name='patient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='soapnote',
            name='body_markers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='soapnote',
            name='wound_chart',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
