# Generated by Django 5.0.6 on 2026-05-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0011_scribesession_nullable_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=120)),
                ('generic_name', models.CharField(db_index=True, max_length=120)),
                ('drug_class', models.CharField(blank=True, help_text='e.g. NSAID, ACE inhibitor, biguanide, PPI, statin', max_length=120)),
                ('jamaican_common', models.BooleanField(default=False, help_text='Tick if this brand is commonly prescribed/used in Jamaica.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Drug aliases',
                'ordering': ('brand_name',),
                'unique_together': {('brand_name', 'generic_name')},
            },
        ),
        migrations.CreateModel(
            name='DrugInteractionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
