# Generated by Django 5.0.6 on 2026-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0016_soapnote_visit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribesession',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
    ]
