# Generated by Django 5.0.6 on 2026-07-08 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
        ('scribe', '0022_encrypt_phi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribesession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scribe_sessions', to='emr.patient'),
        ),
    ]
