# Generated by Django 5.0.6 on 2026-07-11 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0023_scribesession_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_use', models.CharField(blank=True, max_length=10)),
                ('plan_choice', models.CharField(blank=True, max_length=40)),
                ('would_pay', models.CharField(blank=True, max_length=40)),
                ('feature_request', models.TextField(blank=True)),
                ('improve', models.TextField(blank=True)),
                ('hated', models.TextField(blank=True)),
                ('liked', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_feedback', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_feedback', to='scribe.scribesession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
