# Generated by Django 5.0.6 on 2026-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0024_experiencefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribesession',
            name='generate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scribesession',
            name='magic_edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scribesession',
            name='polish_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
