# Generated by Django 5.0.6 on 2026-07-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scribe', '0026_modelusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusagelog',
            name='cached_tokens',
            field=models.PositiveIntegerField(default=0, help_text="Prompt tokens served from Azure's cache (billed cheaper)."),
        ),
    ]
